
# Pedir autores
GET http://localhost:3000/api/authors

###

#  Añadir autores
POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "name": "Juan López",
    "email": "juan.lopez@example.com",
    "image": "https://example.com/images/juan.jpg"
}


###

# Modificar autores
PUT http://localhost:3000/api/authors/4
Content-Type:  application/json

{
    "name": "Ana Gómez",
    "email": "ana.gomez@example.com",
    "image": "https://example.com/images/ana.jpg"
}


###

# Eliminar autores
DELETE http://localhost:3000/api/authors/3



###

#  Pedir todos los posts con la información del autor
GET http://localhost:3000/api/posts


###

#  Pedir posts a partir de un autor.
GET http://localhost:3000/api/posts/author/1


###

# Añadir un nuevo posts
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title": "Título 7",
    "description": "Descripción de la séptima publicación",
    "category": "Caregory7",
    "author_id": 6    

}

###

# Modificar un posts a partir de la Id del post
PUT http://localhost:3000/api/posts/24
Content-Type: application/json

{
    "title": "Título 24",
    "description": "Descripción de la tercera publicación",
    "category": "Caregory3"
    
}


### 

# Eliminar post por Id del post
DELETE http://localhost:3000/api/posts/25
